# Generated by Django 4.2.5 on 2023-09-21 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True)),
                ('titular', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
