# Generated by Django 4.2.5 on 2023-09-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
