# Generated by Django 4.2.5 on 2023-09-21 21:44

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_conta_saldo_alter_users_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.conta', verbose_name=api.models.Conta),
        ),
        migrations.AlterField(
            model_name='conta',
            name='titular',
            field=models.CharField(max_length=50),
        ),
    ]
