# Generated by Django 4.2.5 on 2023-09-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_users_id_account_alter_conta_titular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id_account',
        ),
        migrations.AddField(
            model_name='users',
            name='id_account',
            field=models.ManyToManyField(blank=True, default='', to='api.conta'),
        ),
    ]
