# Generated by Django 4.2.5 on 2023-09-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_users_id_account_users_id_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id_account',
            field=models.ManyToManyField(blank=True, default='', null=True, to='api.conta'),
        ),
    ]
