# Generated by Django 4.2.5 on 2023-09-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_users_id_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id_account',
            field=models.ManyToManyField(blank=True, default='', to='api.conta'),
        ),
    ]
