# Generated by Django 4.2.5 on 2023-10-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_users_hours_create_users_hours_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='hours_create',
        ),
        migrations.RemoveField(
            model_name='users',
            name='hours_modified',
        ),
        migrations.AlterField(
            model_name='users',
            name='data_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='data_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
